name: Render Arabic PDFs

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install TeX Live + Arabic Support
        run: |
          sudo apt update
          sudo apt install -y texlive-xetex texlive-lang-arabic texlive-fonts-extra fonts-amiri

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render PDFs
        run: |
          quarto render Content/_sec_Chapter3_Studying.qmd --to pdf