name: Render PDF

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install LaTeX + Fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-xetex fonts-amiri

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render PDFs
        run: |
          quarto render Content/ --to pdf
